{
  "dependencies": [
    {
      "name": "fastapi",
      "version": "0.104.1",
      "vulns": [
        {
          "aliases": [
            "CVE-2024-24762",
            "GHSA-2jv5-9r88-3w3p",
            "GHSA-qf9m-vfgh-m389"
          ],
          "description": "FastAPI is a web framework for building APIs with Python 3.8+ based on standard Python type hints. When using form data, `python-multipart` uses a Regular Expression to parse the HTTP `Content-Type` header, including options. An attacker could send a custom-made `Content-Type` option that is very difficult for the RegEx to process, consuming CPU resources and stalling indefinitely (minutes or more) while holding the main event loop. This means that process can't handle any more requests. It's a ReDoS(Regular expression Denial of Service), it only applies to those reading form data, using `python-multipart`. This vulnerability has been patched in version 0.109.1.",
          "ecosystem": "python",
          "fix_versions": [
            "0.109.1",
            "9d34ad0ee8a0dfbbcce06f76c2d5d851085024fc"
          ],
          "id": "PYSEC-2024-38",
          "package": "fastapi",
          "references": [
            "https://github.com/tiangolo/fastapi/security/advisories/GHSA-qf9m-vfgh-m389",
            "https://github.com/tiangolo/fastapi/commit/9d34ad0ee8a0dfbbcce06f76c2d5d851085024fc",
            "https://github.com/tiangolo/fastapi/releases/tag/0.109.1"
          ],
          "severity": "unknown",
          "source_id": "PYSEC-2024-38",
          "version": "0.104.1"
        }
      ]
    },
    {
      "name": "uvicorn",
      "version": "0.24.0",
      "vulns": []
    },
    {
      "name": "pydantic",
      "version": "2.5.0",
      "vulns": []
    },
    {
      "name": "sqlalchemy",
      "version": "2.0.23",
      "vulns": []
    },
    {
      "name": "psycopg2-binary",
      "version": "2.9.9",
      "vulns": []
    },
    {
      "name": "aioredis",
      "version": "2.0.1",
      "vulns": []
    },
    {
      "name": "requests",
      "version": "2.31.0",
      "vulns": [
        {
          "aliases": [
            "CVE-2024-47081"
          ],
          "description": "Requests vulnerable to .netrc credentials leak via malicious URLs",
          "ecosystem": "python",
          "fix_versions": [
            "2.32.4"
          ],
          "id": "GHSA-9hjg-9r4m-mvj7",
          "package": "requests",
          "references": [
            "https://github.com/psf/requests/security/advisories/GHSA-9hjg-9r4m-mvj7",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-47081",
            "https://github.com/psf/requests/pull/6965",
            "https://github.com/psf/requests/commit/96ba401c1296ab1dda74a2365ef36d88f7d144ef",
            "https://github.com/psf/requests",
            "https://requests.readthedocs.io/en/latest/api/#requests.Session.trust_env",
            "https://seclists.org/fulldisclosure/2025/Jun/2",
            "http://seclists.org/fulldisclosure/2025/Jun/2",
            "http://www.openwall.com/lists/oss-security/2025/06/03/11",
            "http://www.openwall.com/lists/oss-security/2025/06/03/9",
            "http://www.openwall.com/lists/oss-security/2025/06/04/1",
            "http://www.openwall.com/lists/oss-security/2025/06/04/6"
          ],
          "severity": "medium",
          "source_id": "GHSA-9hjg-9r4m-mvj7",
          "version": "2.31.0"
        },
        {
          "aliases": [
            "CVE-2024-35195"
          ],
          "description": "Requests `Session` object does not verify requests after making first request with verify=False",
          "ecosystem": "python",
          "fix_versions": [
            "2.32.0"
          ],
          "id": "GHSA-9wx4-h78v-vm56",
          "package": "requests",
          "references": [
            "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-35195",
            "https://github.com/psf/requests/pull/6655",
            "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac",
            "https://github.com/psf/requests",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"
          ],
          "severity": "medium",
          "source_id": "GHSA-9wx4-h78v-vm56",
          "version": "2.31.0"
        }
      ]
    },
    {
      "name": "python-multipart",
      "version": "0.0.6",
      "vulns": [
        {
          "aliases": [
            "CVE-2024-24762",
            "GHSA-qf9m-vfgh-m389",
            "PYSEC-2024-38"
          ],
          "description": "python-multipart vulnerable to Content-Type Header ReDoS",
          "ecosystem": "python",
          "fix_versions": [
            "0.0.7"
          ],
          "id": "GHSA-2jv5-9r88-3w3p",
          "package": "python-multipart",
          "references": [
            "https://github.com/Kludex/python-multipart/security/advisories/GHSA-2jv5-9r88-3w3p",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-24762",
            "https://github.com/github/advisory-database/pull/4829",
            "https://github.com/Kludex/python-multipart/commit/20f0ef6b4e4caf7d69a667c54dff57fe467109a4",
            "https://github.com/encode/starlette/commit/13e5c26a27f4903924624736abd6131b2da80cc5",
            "https://github.com/tiangolo/fastapi/commit/9d34ad0ee8a0dfbbcce06f76c2d5d851085024fc",
            "https://github.com/Kludex/python-multipart",
            "https://github.com/andrew-d/python-multipart/blob/d3d16dae4b061c34fe9d3c9081d9800c49fc1f7a/multipart/multipart.py#L72-L74",
            "https://github.com/pypa/advisory-database/tree/main/vulns/fastapi/PYSEC-2024-38.yaml",
            "https://github.com/tiangolo/fastapi/releases/tag/0.109.1"
          ],
          "severity": "high",
          "source_id": "GHSA-2jv5-9r88-3w3p",
          "version": "0.0.6"
        },
        {
          "aliases": [
            "CVE-2024-53981"
          ],
          "description": "Denial of service (DoS) via deformation `multipart/form-data` boundary",
          "ecosystem": "python",
          "fix_versions": [
            "0.0.18"
          ],
          "id": "GHSA-59g5-xgcq-4qw3",
          "package": "python-multipart",
          "references": [
            "https://github.com/Kludex/python-multipart/security/advisories/GHSA-59g5-xgcq-4qw3",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-53981",
            "https://github.com/Kludex/python-multipart/commit/c4fe4d3cebc08c660e57dd709af1ffa7059b3177",
            "https://github.com/Kludex/python-multipart"
          ],
          "severity": "high",
          "source_id": "GHSA-59g5-xgcq-4qw3",
          "version": "0.0.6"
        }
      ]
    },
    {
      "name": "alembic",
      "version": "1.13.1",
      "vulns": []
    }
  ],
  "queries": [
    [
      "fastapi",
      "0.104.1"
    ],
    [
      "uvicorn",
      "0.24.0"
    ],
    [
      "pydantic",
      "2.5.0"
    ],
    [
      "sqlalchemy",
      "2.0.23"
    ],
    [
      "psycopg2-binary",
      "2.9.9"
    ],
    [
      "aioredis",
      "2.0.1"
    ],
    [
      "requests",
      "2.31.0"
    ],
    [
      "python-multipart",
      "0.0.6"
    ],
    [
      "alembic",
      "1.13.1"
    ]
  ],
  "skipped": []
}
